### ISSUE TITLE
The plugin fails to compile with Unreal Engine 5.6.1 due to missing of GENERATED_BODY()

### ISSUE THREAD

**Issue by Cesio137** [GameTechDev/XeSSUnrealPlugin#25]
Command: `RunUAT.bat BuildPlugin -Plugin="C:\Users\natha\Downloads\UE56\XeSS_UE5.6_Plugin_v2.1.1.1\XeSS.uplugin" -Package="C:\Users\natha\Downloads\UE56\XeSS_UE5.6_Plugin_v2.1.1.1\Package" -TargetPlatforms=Win64 -VS2022`

```bash
[16/107] Compile [x64] SharedPCH.UnrealEd.Cpp20.cpp
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(727,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_USTRUCT_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(1270,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(1302,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(1682,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(1769,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(1830,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(1861,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(1881,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2060,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2079,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2107,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2114,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2130,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2214,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2310,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2381,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2401,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2436,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2636,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2671,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2825,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2956,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_USTRUCT_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(2989,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_USTRUCT_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3155,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_USTRUCT_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3188,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_USTRUCT_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3245,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_USTRUCT_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3434,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3601,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3614,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3655,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3683,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3768,7): error C2143: syntax error: missing ';' before '<class-head>'
class UEngineTypes : public UObject
      ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3768,20): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
class UEngineTypes : public UObject
                   ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3770,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_UCLASS_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3826,1): error C2143: syntax error: missing ';' before '<class-head>'
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FConstraintBrokenSignature, int32, ConstraintIndex);
^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3826,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3826,1): error C3861: 'FConstraintBrokenSignature_DelegateWrapper': identifier not found
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3829,1): error C2143: syntax error: missing ';' before '<class-head>'
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FPlasticDeformationEventSignature, int32, ConstraintIndex);
^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3829,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3829,1): error C3861: 'FPlasticDeformationEventSignature_DelegateWrapper': identifier not found
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3838,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3854,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3880,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(3982,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(4041,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(4064,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
        ^
C:\Program Files\Epic Games\UE_5.6\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h(4150,2): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
        GENERATED_BODY()
```

**Comment by Cesio137** [comment]
[logs.txt](https://github.com/user-attachments/files/22036022/logs.txt)

**Comment by Cesio137** [comment]
Sorry, this happened because I had an old version of the toolchain selected, and it was being used during the build.
