### ISSUE TITLE
The plugin fails to compile with Unreal Engine 5.6.1 due to a missing include dependency.

### ISSUE THREAD

**Issue by kurosagi591** [GameTechDev/XeSSUnrealPlugin#22]
**Details:**
When building the XeSS plugin version 2.1.1 with UE 5.6.1, the following error occurs:

fatal error C1083: Cannot open include file: 'RHIDiagnosticBuffer.h': No such file or directory

This is triggered by the inclusion of `VulkanQueue.h`, which references `RHIDiagnosticBuffer.h`. In UE 5.6.1, this header has been moved to the `RHICore` module (`Engine/Source/Runtime/RHICore/Public`), but several plugin modules do not declare `RHICore` as a dependency in their `.Build.cs` files.

**Suggested Fix:**
Add `"RHICore"` to the `PublicDependencyModuleNames` in the affected modules, such as:
- `XeSSVulkanRHI.Build.cs`
- `XeSSUnreal.Build.cs`
- XeSSCore.Build.cs
- Any other module that includes `VulkanQueue.h`

After adding the missing dependency, the plugin compiles successfully with UE 5.6.1.

**Environment:**
- Unreal Engine version: 5.6.1 (source build)
- XeSS plugin version: 2.1.1
- OS: Windows 11
- Compiler: MSVC 14.38.33130 (Visual Studio 2022 Enterprise)

Thanks for your work on this plugin — it’s a great addition to UE!
